### ISSUE TITLE
May you add more functions?

### ISSUE THREAD

**Issue by CyberFork** [nimadez/voxel-builder#1]
It's a great pleasure to learn about this project and to know a developer like you. I love this editor in all aspects. It's an amazing application.
In the process of using it, I noticed a few functions that would be great to be included, such as adding and undoing blocks in batches. 
Would you consider including these functions in the coming future?

**Comment by nimadez** [comment]
Definitely sure,
I'm busy right now, moving into a new house, I will update it as soon as possible.
Thanks, you're welcome

**Comment by nimadez** [comment]
I'm still busy, new 'Memory Steps' added to undo/redo 10 steps, similar to Zbrush!

**Comment by nimadez** [comment]
I'm still busy, new 'Memory Steps' added to undo/redo 10 steps, similar to Zbrush!
