### ISSUE TITLE
Hello, you can consider supporting Kenney assets

### ISSUE THREAD

**Issue by robomentor** [nimadez/voxel-builder#16]
It would be great if you could support importing assets to build the world
https://kenney.nl/assets?q=3d

**Comment by nimadez** [comment]
I'm sorry it doesn't work like that, I mean technically impossible, this application designed to create the asset not the world itself,
If you look at the Babylon.js engine sources and examples, you can find a better solution to build the world using your assets,
You have a nice and clean assets btw, thanks
