### ISSUE TITLE
Implement real voxel.

### ISSUE THREAD

**Issue by twoco** [nimadez/voxel-builder#2]
This is not really Voxel.

![image](https://user-images.githubusercontent.com/53160891/133941740-b261120f-9731-47c0-9b9f-32a145265d38.png)

![voxel](https://user-images.githubusercontent.com/53160891/133941847-60f5d942-94bb-492c-a239-ca76ed9da10b.png)

Don't use the term Voxel for this. Misleading in Babylon.js demos.

Or did I miss something?

**Comment by nimadez** [comment]
I think you didn't understand the project, a voxel represents a single data point, this data point can consist of anything!
In this project, voxel is just a position and color, we build the mesh later by SPS particles to achieve maximum performance.
