### ISSUE TITLE
Good work.

### ISSUE THREAD

**Issue by hannahroksanne** [nimadez/voxel-builder#24]
Your work on voxel-builder is insanely good.

I've been getting my ass kicked for weeks in my attempt to build an efficient, featureful voxel editor. It is a really difficult task. (I have no background with three or any 3D tools.)

I've looked at countless other repos, they're mainly all just clones of a three example with some things added, but nothing viable. But yours is the most commendable editor on Github. It is a fully working competitor to all of the big dogs in the voxel editor game.

I applaud you!

**Comment by nimadez** [comment]
Thank you and I'm glad you found it interesting. Of course, this application was made without prior planning and even if it excels in the web browser, it will never reach a masterpiece like MagicaVoxel. If you have an opinion or suggestion, be sure to raise it.
