### ISSUE TITLE
This is amazing! How can we add serverside bindings ?

### ISSUE THREAD

**Issue by fire17** [nimadez/voxel-builder#4]
OK so first off this repo is amazing
the visuals look super clean and modern
works superfast, full navigation, raycasting mouse picking, 2D over 3D
it works on the browser online,  , RUNS as gh-pages with 0 cost, instant demo

i lliterally wish that every software looked and felt like that, seriously

the only thing that this lacks is a proper way to connect with a server (like with websockets socketio etc)
I'd love to see if anyone has some referenced to how to make it work
if data can be requested from another server
and the server can push data to the scene
then you could make literally anything
any visuallization, where the server can update the site view whenever (realtime updates)
and the user can influence and send data to the server in realtime
simple examples.. realtime chatrooms, minecraft online, sketchup, blender, photoshop online you name it

my hope is to get a working python server that interacts with a js website with a good 3d visualization framework
this includes bridging node with python (some solutions out there that i shall test)
and also having a well developed web based "game engine" (that can handle the rendering as well as being interactive) that can utilzed bindings to the backend

Currenly planing.
1. to see if i can use node to interact with this simulated environment - to get events when user does actions + to request client side to be updated with serverside-rendered scene (or data equivelent)
2. If 1 works, bridge the bindings into python

the goal is to create a portal website that can ask the server to give it a specific view (or subpage) and the site will seamlessly transform to the desired layout (like your site for example) and user actions are triggering events to the server (hopefully all managed and generated with python and client side hosted on gh-pages)

PS. how can i use the mouse to pick and move objects around (thought that pickable does that)?

**Comment by nimadez** [comment]
Welcome, thank you for the feedback,
Yes, it is possible to store data server-side using python in real-time, basically just need to import "voxels" array, which contain XYZ positions and a hex color for each voxel, just like how Memory Steps and localStorage works.
Unfortunately, I can't pay for a host/domain at the moment, they are pretty expensive in my country.
Regarding mouse picking, you can't move voxels around freely, there is a Transform tool, but I think it is possible to have a free drawing mode, I can work on it.
btw, you have a nice looking website!
Cheers

**Comment by fire17** [comment]
ok im sharing my vision with you
just so you know what you got is the closest i've seen to a working technology that i need to utilize (referenced below)
I've got a server that is not very active you could use for this
i'd love to get intouch if you feel its appropriate, to chat about the possibilites
hopefully to make a new amazing foss colab
im making a link that refers to my whatsapp (leme know if you prefer a different platform)
this link is a dynamic referral, therefor ill turn it off later, to not get spammed or expose my personal number
[https://rebrand.ly/nimadezXfire17](https://rebrand.ly/nimadezXfire17) (goes to wa.me/mynumber)
furthermore, ive written down how i see this going down, and i feel sharing it publicly will be alright
its long but comprehensive (and hopefully coherent)

### 0 Cost State of the Art Instant Website Builder Website

How do you combine the 3D visual capabilites of JS (babylon.js/threejs)
with realtime the feedback and control of (nuxt/react.js)
that is free hosted (github-pages) and automatically managed (netlifycms)

ok so this is big but
the goal is to chain together existing modern FOSS to generate a website/webapp building platform
(such as a free wix) the is modern enough to webgame-esk realtime 3D graphics
along with realtime server-client and client-client communication
which can generate and store subpages and or edit them visually on the site
all of which (server and client) are store and hosted on a free git hosting service (such as gh-pages)

so far i've managed to narrow down what im guessing  are most of the relevant technologies
from server to client
nodejs for server (*hopefully with python bindings)
babylon.js or threejs for vis
- need to find how to bind vis to server dynamicly (ie socketio/websockets)
create a good interactable base scene editor - best closest foss example: https://nimadez.github.io/voxel-builder/
scenes can request to load data from the original server/3rd party server/sites
scene template can be saved (with git/netlify/netifycms) and auto hosted on gh-page
both the editor and the saved websites/webapps should be using the same stack
all pages are interactive and 

this could be the key to serverless standalone foss websites and apps
the key that everythings is super modern, hence easy to build, great looking, super fast & secure
I could see people building Operating System Websites where people could fork or weakref the os, create a secure user account, and have no-machine desktop tailored to them, mimiking the look and feel of common os (linux/mac/win) or completely novel ones.
Updates are transparent to the end-user and are always maintained
everything backed up regularly, seamlessly, always secured, and free
complex apps such as photo or video editing , music mixing, engineering tools could outsource to serveside computation but all other computation is done on the client-side

**Comment by nimadez** [comment]
Well, long road ahead! :)
I'd like to keep my personal/fun projects clean and simple with minimum to zero dependencies, so I can manage them later in my spare time, because I'm very busy with job and family.
But I will contact you and let me know if I can help you in any way.
