### ISSUE TITLE
rendering lag

### ISSUE THREAD

**Issue by kpwa** [nimadez/voxel-builder#7]
Great job on this app & continuous updates. Your recent release (3.9.7) caused the app to run slow from 60fps all the way to 7fps.

**Comment by nimadez** [comment]
Thank you for the report,
can you provide more information?
because I can't replicate the issue on the latest desktop/android Chrome browsers, or Electron on desktop.

**Comment by nimadez** [comment]
@kpwa version 3.9.7 uses "ContactHardeningShadow" which may cause problems or slow down in some cases.
There has also been a report of shadow artifacts.
ContactHardeningShadow removed.
Please try again and report, thanks
