### ISSUE TITLE
Support in vengi added

### ISSUE THREAD

**Issue by mgerhardy** [nimadez/voxel-builder#8]
Not really an issue - just wanted to let you know that I've added support to vengi for your voxel format.

https://github.com/mgerhardy/vengi/blob/master/src/modules/voxelformat/VBXFormat.h

https://mgerhardy.github.io/vengi/Formats/

**Comment by nimadez** [comment]
Great job and hard work, very nostalgic for me.
I add a link to **_vengi_** and **_github.com/mgerhardy/vengi_** in the readme file.
I can add an importer for the vengi format if it can be read as binary, see _**parseMagicaVoxel()**_ 
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to vengi and github.com/mgerhardy/vengi in the readme file.
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to **_vengi_** and **_github.com/mgerhardy/vengi_** in the readme file.
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to **_vengi_** in the readme file
I can add an importer to VB if you have a format that can be read in binary.
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to vengi in the readme file
I can add an importer to VB if you have a format that can be read in binary
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to **_vengi_** in the readme file
I can add an importer to VB if you have a format that can be read as binary
Thank you

**Comment by nimadez** [comment]
Great job and hard work,
I add a link to **_vengi_** in the readme file
I can add an importer to VB if you have a format that can be read
Thank you

**Comment by nimadez** [comment]
I add a link to **vengi** in the readme file
I can add an importer to VB if you have a format that can be read
Thank you

**Comment by nimadez** [comment]
Added a link to **vengi** in the readme file
I can add an importer to VB if you have a format that can be read
Thank you

**Comment by nimadez** [comment]
A dedicated [wiki page](https://github.com/nimadez/voxel-builder/wiki/VBX-Format) has been created for the VBX format, including a link to vengi.
